GET http://localhost:8080/api/admin/welcome
Accept: application/json
Authorization: {{token}}

###
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "identityNo": "erjiangao",
  "password": "erjiangao"
}

> {% client.global.set("token", response.headers.valueOf("Authorization")); %}

###
