POST http://localhost:8080/api/login
Content-Type: application/json

{
  "identityNo": "201701",
  "password": "201701"
}

> {% client.global.set("token", response.headers.valueOf("authorization")); %}

### 学生登录